# ***************************************************************************
# MAKEFILE.MSVC (c) Copyright Roger Bowler, 2005
# Build Hercules for Win32 using MSVC and nmake (static link version)
#
# $Id: makefile.msvc,v 1.8 2006/12/08 09:43:29 jj Exp $
#
# $Log: makefile.msvc,v $
# Revision 1.8  2006/12/08 09:43:29  jj
# Add CVS message log
#
#
# ***************************************************************************
!include makefile-dllmod.msvc
